model:
  pretrained_model_path: "/data1/linkdom/.cache/huggingface/hub/models--Qwen--Qwen2.5-Math-1.5B-Instruct/snapshots/aafeb0fc6f22cbf0eaeed126eff8be45b0360a35"
  device: "cuda"
  dtype: "bfloat16"
data:
  path: "/data1/linkdom/.cache/huggingface/hub/datasets--Jiayi-Pan--Countdown-Tasks-3to4/snapshots/408f70d177020686d34a56bba5952feb45aaaee4"
  test_size: 128
training:
  random_seed: 1337
  max_prompt_len: 256
  max_gen_len: 1024
  batch_size: 256
  num_questions_per_batch: 32
  # Number of examples per gradient accumulation step
  micro_batch_size: 2
  max_grad_norm: 1.0
  learning_rate: 1.0e-5
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ckpt_dir: "/data2/linkdom/checkpoints/srgrpo-qwen2.5-math-1.5b-instruct"
  log_dir: "logs"
  skip_unfinished_episodes: true
  ckpt_save_interval: 100
  eval_interval: 10
  memory_efficient_adamw: false